### ISSUE TITLE
New fava version breaks fava_dashboards

### ISSUE THREAD

**Issue by francocalvo** [andreasgerstmayr/fava-dashboards#8] opened 2023-07-21 15:08 UTC
Hi! Apparently, v1.2.5 breaks fava_dashboards. For example, I've seen that `FavaAPIException` is not `FavaAPIError` in `helpers.py`. After fixing that, I got this error:

```
Traceback (most recent call last):
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/fava/application.py", line 327, in extension_report
    content = Markup(render_template_string(template, extension=ext))
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/flask/templating.py", line 163, in render_template_string
    return _render(app, template, context)
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 26, in top-level template code
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/fava/application.py", line 136, in url_for
    return _cached_url_for(endpoint, **values)
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/flask/helpers.py", line 225, in url_for
    return current_app.url_for(
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/calvo/Nextcloud/Finanzas/Beans/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'extension_report' with values ['bfile', 'dashboard', 'report_name']. Did you forget to specify values ['extension_name']?
```

I'd like to help fix it. I'm going to work right now, but I'll take another crack at it tomorrow if you want.

**Comment by andreasgerstmayr** [comment] 2023-07-26 20:39
Resolved by #9 (already merged).

**Closed by andreasgerstmayr** 2023-07-26 20:39 UTC

**Comment by addisonklinke** [comment] 2023-08-04 08:55
I'm using `fava==1.25.1` and seeing this error when trying to launch `fava_dashboards`

```
Importing module "fava_dashboards" failed. 
Error: "cannot import name 'FavaAPIError' from 'fava.helpers'
(/home/addison/venv/beancount/lib/python3.9/site-packages/fava/helpers.py)"
```

Oddly enough the class exists in the mentioned file

```
$ grep FavaAPIError /home/addison/venv/beancount/lib/python3.9/site-packages/fava/helpers.py
class FavaAPIError(Exception):
```

Any thoughts?

**Comment by andreasgerstmayr** [comment] 2023-08-05 21:11
@addisonklinke I cannot reproduce this error with fava 1.25.1. Can you try deleting the venv and re-installing everything?

**Comment by addisonklinke** [comment] 2023-08-07 12:00
Restarted my Fava server and that fixed the issue (in comparison re-loading did not)

**Comment by addisonklinke** [comment] 2023-08-07 12:03
Follow-up question - are changes to `dashboards.yaml` expected to be picked up by Fava's re-load detection? I see the yellow icon if I alter my `.beancount` file(s), but no prompt for changing dashboards. Manually refreshing the page works though

**Comment by andreasgerstmayr** [comment] 2023-08-08 20:11
> Follow-up question - are changes to `dashboards.yaml` expected to be picked up by Fava's re-load detection?

No, afaics that only works for beancount files.
